name = "All4forCloud"
license = "MIT"
licenselink = "https://github.com/chipzoller/hugo-clarity/blob/master/LICENSE.md"
description = "All4forCloud - Tips & Tricks about the Microsoft Azure Cloud and Me :)"
homepage = "https://github.com/chipzoller/hugo-clarity"
tags = ["blog", "technical", "simple", "dark", "syntax highlighting"]
features = ["blog", "technical", "simple", "dark", "syntax highlighting"]
min_version = "0.63.0"
